networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  matomo:
    image: matomo:5-fpm
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - "MATOMO_DATABASE_HOST=${DB_HOST}"
      - "MATOMO_DATABASE_USERNAME=${DB_USERNAME}"
      - "MATOMO_DATABASE_PASSWORD=${DB_PASSWORD}"
      - "MATOMO_DATABASE_DBNAME=${DB_NAME}"
    depends_on:
      - mariadb
    volumes:
      - .docker/data/matomo:/var/www/html

  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    restart: unless-stopped
    networks:
      - app
      - frontend
    depends_on:
      - matomo
    volumes:
      - ./.docker/templates:/etc/nginx/templates:ro
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - .docker/data/matomo:/var/www/html:z,ro
    environment:
      NGINX_FPM_SERVICE: ${COMPOSE_PROJECT_NAME}-matomo-1:9000
      NGINX_WEB_ROOT: /var/www/html
      NGINX_PORT: 8080
      NGINX_MAX_BODY_SIZE: 5M
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
